services:
  postgres:
    image: postgis/postgis:17-master
    container_name: LangZ
    restart: unless-stopped

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: LangZ

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d LangZ"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

  # psql -h localhost -p 5432 -U postgres -d LangZ